name: GitHub Release

on:
    push:
        tags: "*"
        branches:
            - "!*"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  lfs: true

            - name: Fetch Tags
              run: git fetch --prune --unshallow --tags

            - name: Set Variables
              run: |
                  echo "VERSION=$(git describe --tags)" >> $GITHUB_ENV
                  git log --format=%B -n 1 $(git log -1 --pretty=format:"%h") | cat - > changes.txt

            - name: Create Mod Zipfile
              run: |
                  git lfs install
                  git lfs fetch
                  git lfs checkout
                  ./gradlew release

            - name: Publish Release on GitHub
              uses: "ncipollo/release-action@v1"
              with:
                  name: ${{ env.VERSION }}
                  tag: ${{ env.VERSION }}
                  bodyFile: changes.txt
                  draft: false
                  prerelease: false
                  token: ${{ secrets.GITHUB_TOKEN }}
                  artifacts: "stelnet*.zip"
