name: Tests

on:
    pull_request:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  lfs: true

            - name: Run Tests
              run: |
                  chmod +x gradlew
                  ./gradlew test
